name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.GENESYS_SAMPLES_SP}}

      - name: Upload Hugo
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob directory create --account-name 'genesysworkshops' -c $web -d ${{ github.repository }}
            az storage blob upload-batch --account-name 'genesysworkshops'--source '${{ env.WORKING_DIRECTORY }}/public' --destination '$web/${{ github.repository }}/'
